/*
        Joshua Whitney  
        MIU 1306 
        Assignement 1
 */

var json = {
    "zombieTemp1": {
        "fname": ["First Name:", "Josh"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "jwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "Ralph"],
        "zlast": ["Zombies Last Name:", "Brainstein"],
        "sex":   ["Zombies Sex:", "Male"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Grenade"],
        "write": ["Users Reason:", "Just Because"],
        "rate":  ["User Rating:", "10"],
        "date":  ["You Want Them Killed on:", "June 3, 2013"],
        "inv":   ["Customer Reputation:", "Low"]
    },
    "zombieTemp2": {
        "fname": ["First Name:", "Mike"],
        "lname": ["Last Name:", "Howe"],
        "email": ["Email Address:", "howeinsane@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "bob"],
        "zlast": ["Zombies Last Name:", "armLicker"],
        "sex":   ["Zombies Sex:", "Male"],
        "prior": ["Priority:", "NO"],
        "weap":  ["Weapon of Choice:", "Crowbar"],
        "write": ["Users Reason:", "hes an idiot!"],
        "rate":  ["User Rating:", "4"],
        "date":  ["You Want Them Killed on:", "July 18, 2013"],
        "inv":   ["Customer Reputation:", "Medium"]
    },
    "zombieTemp3": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp4": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp5": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp6": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp7": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp8": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp9": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp10": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp11": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp12": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp13": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp14": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp15": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp16": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp17": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp18": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp19": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    },
    "zombieTemp20": {
        "fname": ["First Name:", "Louise"],
        "lname": ["Last Name:", "Whitney"],
        "email": ["Email Address:", "lwhitney@gmail.com"],
        "tele":  ["Telephone Number:", "123-456-7890"],
        "zname": ["Zombies First Name:", "jina"],
        "zlast": ["Zombies Last Name:", "toeTaster"],
        "sex":   ["Zombies Sex:", "Female"],
        "prior": ["Priority:", "YES"],
        "weap":  ["Weapon of Choice:", "Bazooka"],
        "write": ["Users Reason:", "Shes crazy!"],
        "rate":  ["User Rating:", "6"],
        "date":  ["You Want Them Killed on:", "August 10, 2013"],
        "inv":   ["Customer Reputation:", "High"]
    }
}
